# Generated by Django 4.0.3 on 2022-05-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadservice', '0003_carengineers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carengineers',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
