# Generated by Django 4.0.3 on 2022-05-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadservice', '0004_alter_carengineers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carengineers',
            name='garage_location',
            field=models.CharField(choices=[('location', 'location'), ('GreaterAccraRegion', 'GreaterAccraRegion'), ('CenterRegion', 'CenterRegion'), ('AhafoRegion', 'AhafoRegion'), ('AshantiRegion', 'AshantiRegion'), ('BonoEastRegion', 'BonoEastRegion'), ('BrongAhafoRegion', 'BrongAhafoRegion'), ('VoltaRegion', 'VoltaRegion'), ('OtiRegion', 'OtiRegion'), ('SavannahRegion', 'SavannahRegion'), ('UpperEastRegion', 'UpperEastRegion'), ('WesternRegion', 'WesternRegion'), ('NorthernRegion', 'NorthernRegion')], default='location', max_length=40, unique=True),
        ),
    ]
